routes/web.php
if(!defined('ROOT_DIR_NAME')) define('ROOT_DIR_NAME','');
if(!defined('DEFAULT_USER')) define('DEFAULT_USER','');
if(!defined('LOGO_DARK')) define('LOGO_DARK','assets/icons/delta-dark.png');
if(!defined('LOGO_WHITE')) define('LOGO_WHITE','assets/icons/delta-white.png');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// BASE ROUTES
Route::get('/', 'HomeController@index')->name('home');
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');

Route::get('/profile/{status?}', ['uses'=>'ProfileController@get_profile','as'=>'profile']);
Route::post('/update/profile', ['uses'=>'ProfileController@post_profile','as'=>'update_profile']);

Route::group(['prefix' =>ROOT_DIR.'user', 'middleware' => ['auth','can:administration'], 'as' => 'user.'], function () {
    Route::get('/register', ['uses'=>'Auth\RegisterController@showRegistrationForm','as'=>'register']);

    //user edit route here
    Route::get('/edit/{action}', ['uses'=>'Auth\RegisterController@showEditForm','as'=>'edituser']);
    Route::post('/register', 'Auth\RegisterController@register');

    Route::get('/list', ['uses'=>'Auth\RegisterController@index', 'as'=>'index']);
    Route::post('/permission_view', ['uses'=>'PermissionController@permission_view', 'as'=>'permission_view']);
    Route::get('/assign_permission/{id}', ['uses'=>'PermissionController@assign_permission', 'as'=>'assign_permission']);
    Route::post('/assign_permission/store', ['uses'=>'PermissionController@assign_permission_store', 'as'=>'assign_permission_store']);
    Route::post('/delete', ['uses'=>'Auth\RegisterController@delete', 'as'=>'delete']);
});

Route::group(['prefix' =>ROOT_DIR.'permission', 'middleware' => 'auth', 'as' => 'permission.'], function () {
    Route::get('/list', ['uses'=>'PermissionController@index','as'=>'index'])->middleware('can:user-add');
    Route::post('/add', ['uses'=>'PermissionController@create','as'=>'add'])->middleware('can:user-add');
    Route::post('/delete', ['uses'=>'PermissionController@delete','as'=>'delete'])->middleware('can:user-add');
});

Route::group(['prefix' =>ROOT_DIR.'file', 'middleware' => 'auth', 'as' => 'file.'], function () {
    Route::get('/status', ['uses'=>'FileController@get_file_status','as'=>'get_file_status']);
    // files count @MR
    Route::get('/count', ['uses'=>'FileController@getCount','as'=>'get_files_count']);
    Route::get('/ward_files/{id}', ['uses'=>'FileController@showFilesByWard','as'=>'get_files_by_ward']);
});

// CONSULTANCY ROUTE START
Route::group(['prefix' =>ROOT_DIR.'consultancy', 'middleware' => ['auth','can:consultancy'], 'as' => 'consultancy.'], function () {
    Route::get('/list', ['uses'=>'ConsultancyController@index','as'=>'index'])->middleware('can:consultancy');
    Route::get('/draft', ['uses'=>'ConsultancyController@get_draft','as'=>'draft'])->middleware('can:consultancy');
    Route::get('/add_form_personalinfo/{form_id?}', ['uses'=>'ConsultancyController@get_form_personalinfo','as'=>'add_form_personalinfo'])->middleware('can:consultancy');
    Route::post('/add_form_personalinfo', ['uses'=>'ConsultancyController@post_form_personalinfo','as'=>'store_form_personalinfo'])->middleware('can:consultancy');
    Route::get('/view_form/{form_id}', ['uses'=>'ConsultancyController@get_full_form','as'=>'view_full_form'])->middleware('can:consultancy');

    //form_landinfo routes
    Route::get('/add_form_landinfo/{form_id}', ['uses'=>'ConsultancyController@get_form_landinfo','as'=>'add_form_landinfo'])->middleware('can:consultancy');
    Route::get('/add_form_landinfo/{form_id}', ['uses'=>'ConsultancyController@get_form_landinfo','as'=>'add_form_landinfo'])->middleware('can:consultancy');
    Route::post('/add_form_landinfo', ['uses'=>'ConsultancyController@post_form_landinfo','as'=>'store_form_landinfo'])->middleware('can:consultancy');

    //page = 3 form_buildinginfo
    Route::get('/add_form_buildinginfo/{form_id}', ['uses'=>'ConsultancyController@get_form_buildinginfo','as'=>'add_form_buildinginfo'])->middleware('can:consultancy');
    Route::post('/add_form_buildinginfo', ['uses' => 'ConsultancyController@post_form_buildinginfo' , 'as' => 'store_form_buildinginfo'])->middleware('can:consultancy');

    //page = 4 form_floorinfo
    Route::get('/add_form_floorinfo/{form_id}', ['uses'=>'ConsultancyController@get_form_floorinfo','as'=>'add_form_floorinfo'])->middleware('can:consultancy');
    Route::post('/store_form_floorinfo', ['uses' => 'ConsultancyController@post_form_floorinfo' , 'as' => 'store_form_floorinfo'])->middleware('can:consultancy');

    //page = 5 form_buildingfiles
    Route::get('/add_form_buildingfiles/{form_id}', ['uses'=>'ConsultancyController@get_form_buildingfiles','as'=>'add_form_buildingfiles'])->middleware('can:consultancy');
    Route::post('/add_form_buildingfiles', ['uses' => 'ConsultancyController@post_form_buildingfiles' , 'as' => 'store_form_buildingfiles'])->middleware('can:consultancy');

    // rejected files
    Route::group(['prefix' =>'rejected', 'as'=>'rejected.'], function () {
        Route::get('/list', ['uses' => 'ConsultancyController@get_rejected_file' , 'as' => 'list'])->middleware('can:consultancy');

        //edit form
        Route::get('/edit_form/{form_id}', ['uses'=>'ConsultancyController@get_edit_form','as'=>'edit_form'])->middleware('can:consultancy');
        Route::post('/edit_form', ['uses'=>'ConsultancyController@post_edit_form','as'=>'post_edit_form'])->middleware('can:consultancy');

        //route to edit dpc
        Route::get('/edit_dpcform/{form_id}', ['uses'=>'ConsultancyController@get_edit_dpcform','as'=>'edit_dpcform'])->middleware('can:consultancy');

        //route to edit sampanna
        Route::get('/edit_sampanna/{form_id}', ['uses'=>'ConsultancyController@get_edit_sampanna','as'=>'edit_sampanna'])->middleware('can:consultancy');
    });

    // DPC
    Route::get('/list/dpc/{form_id}', ['uses'=>'ConsultancyController@get_dpc_form','as'=>'get_dpc_form'])->middleware('can:consultancy');
    Route::post('/dpc', ['uses'=>'ConsultancyController@post_dpc_form','as'=>'post_dpc_form'])->middleware('can:consultancy');
    Route::get('/dpc_view/{form_id}', ['uses'=>'ConsultancyController@get_dpc_view','as'=>'get_dpc_view'])->middleware('can:consultancy');
    Route::get('/view_dpc/{form_id}', ['uses'=>'ConsultancyController@get_upload_dpc','as'=>'view_dpc'])->middleware('can:consultancy');

    //dpc after print upload
    Route::post('/upload_dpc', ['uses'=>'ConsultancyController@post_upload_dpc','as'=>'uploaddpc'])->middleware('can:consultancy');

    // SAMPANNA
    Route::get('/sampanna/{form_id}', ['uses'=>'ConsultancyController@get_sampanna_form','as'=>'get_sampanna_form'])->middleware('can:consultancy');
    Route::post('/store_form_sampanna', ['uses'=>'ConsultancyController@post_form_sampanna','as'=>'store_form_sampanna'])->middleware('can:consultancy');
    Route::get('/upload_sampanna/{form_id}', ['uses'=>'ConsultancyController@get_upload_sampanna_form','as'=>'get_upload_sampanna_form'])->middleware('can:consultancy');

    //sampanna after print upload
    Route::post('/upload_sampanna', ['uses'=>'ConsultancyController@post_upload_sampanna','as'=>'uploadsampanna'])->middleware('can:consultancy');
    Route::get('/view_sampanna/{form_id}', ['uses'=>'ConsultancyController@get_view_sampanna','as'=>'view_sampanna'])->middleware('can:consultancy');

    //change house_map
    Route::get('/view_housemap/{form_id}', ['uses'=>'ConsultancyController@get_housemap','as'=>'view_housemap'])->middleware('can:consultancy');
    Route::post('/change_housemap', ['uses'=>'ConsultancyController@post_change_housemap','as'=>'change_housemap'])->middleware('can:consultancy');
});

// AAMIN ROUTE
Route::group(['prefix' =>ROOT_DIR.'aamin', 'middleware' => 'auth', 'as' => 'aamin.'], function () {
    Route::get('/list', ['uses'=>'AaminController@index','as'=>'index'])->middleware('can:aamin');
    Route::get('/view_sandhir/{form_id}', ['uses'=>'AaminController@get_sandhir','as'=>'view_sandhir'])->middleware('can:aamin');
    Route::post('/view_sandhir', ['uses' => 'AaminController@store_aaminPratibedan' , 'as' => 'store_aaminPratibedan'])->middleware('can:aamin');
    Route::get('/view_aamin_pratibedan/{form_id}', ['uses' => 'AaminController@get_aaminPratibedan' , 'as' =>'view_aamin'])->middleware('can:aamin');

    //to display the rejected files.
    Route::get('/list_rejected', ['uses' => 'AaminController@get_rejected_file' , 'as' =>'list_rejected'])->middleware('can:aamin');

    //to edit the aamin_pratibedan form.
    Route::get('/edit_form/{form_id}', ['uses' => 'AaminController@editAaminPratibedan' , 'as' =>'edit_aaminPratibedan'])->middleware('can:aamin');

    //to store uploaded aamin_pratibedan form
    Route::post('/aamin_pratibedan_upload', ['uses' => 'AaminController@store_aaminPratibedanUpload' , 'as' => 'upload_aaminPratibedan'])->middleware('can:aamin');

    //to view both file after upload amin_pratibedan form.

resources/views/consultancy/edit_housemap.blade.php
@extends('layouts.app')
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'plugins/bower_components/dropify/dist/css/dropify.min.css') }}">
    <style>
        .img-rounded {
            border-radius: 6px;
            padding: 5px;
        }

        .option1{
            background-color: transparent;
            padding: 1px;
            width: 20px;
            border: none;
            font-size: 14px;
            color: #333;
            text-align: center;"
        }

        .option2{
            background-color: transparent;
            padding: 1px;
            width: 45px;
            border: none;
            font-size: 14px;
            color: #333;
            text-align: center;"
        }
    </style>
@endsection
@section('page_title')
    नयाँ नक्शा दरखास्त फाईल
@endsection
@section('right_button')
@stop
@section('content-title')
    <h4>नयाँ नक्शा दरखास्त फाईल</h4>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="white-box">
                <div class="panel panel-info">
                    <div class="panel-wrapper collapse in" aria-expanded="true">
                        <div class="panel-body">
                            <form action="{{ route('consultancy.change_housemap') }}" method="post" enctype="multipart/form-data">
                                @csrf
                                <input type="hidden" value="{{$formData->form_id}}" name="form_id">
                                <div class="form-body">



                                    {{-- form_buildingfiles START --}}
                                    <div class="row">
                                        <p style="font-size: 25px; text-align: center"> समंन्धित कागज पत्र</p>
                                        <hr>

                                        <div class="col-md-3">
                                            <div class="form-group ">
                                                <label for="house_map" class="control-label">
                                                    <p style="font-size: 20px;">घरको नक्शा </p>
                                                </label>
                                                <div class="row">
                                                    <input type="file" name="house_map" id="input-file-now-custom-1"  class="dropify" accept=".pdf" data-default-file="{{ asset(STATIC_DIR.'storage/'.$formData->house_map) }}" />
                                                </div>

                                                @if($errors->has('house_map'))
                                                    <span class="text-danger">{{ $errors->first('house_map') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                {{-- end form-body --}}
                                <div class="row">
                                    <div class="col-md-4 ">

                                        <a href="{{ route('consultancy.index') }}" class="btn btn-info btn-outline m-r-5"><i class="fa fa-reply"></i> Back</a>
                                        <button type="submit" class="btn btn-primary btn-outline m-r-5">Update</button>
                                    </div>
                                </div>

                            </form>
                    </div>
                    {{-- end panel --}}


                </div>

            </div>
        </div>
    </div>
    </form>
    </div>


    @include('permission.model')
@endsection

@section('scripts')
    <script src="{{ asset(STATIC_DIR.'plugins/bower_components/dropify/dist/js/dropify.min.js')}}"></script>

    <script>
        $("#option").on ('change',  function( e ){
            var data = $('#option').val();

            if( data == 'मैले') {
                $('#option_1').val('छु');
                $('#option_2').val('छौं');
            }
            else {
                $('#option_1').val('छौं');
                $('#option_2').val('गर्दछौं');
            }
        });

        $(document).ready(function( e ){
            var data = $('#option').val();

            if( data == 'मैले') {
                $('#option_1').val('छु');
                $('#option_2').val('छौं');
            }
            else {
                $('#option_1').val('छौं');
                $('#option_2').val('गर्दछौं');
            }
        });


        // $("#floor_number").on ('change',  function( e ){
        var data = $('#floor_number').val();

        if(data == 1) {
            $('#floor1').show();
            $('#floor2').show();
            $('#floor3').hide();
            $('#floor4').hide();
            $('#floor5').hide();
            $('#floor6').hide();
            $('#floor7').hide();

        }

        if(data == 2) {
            $('#floor1').show();
            $('#floor2').show();
            $('#floor3').show();
            $('#floor4').hide();
            $('#floor5').hide();
            $('#floor6').hide();
            $('#floor7').hide();
        }

        if(data == 3){
            $('#floor1').show();
            $('#floor2').show();
            $('#floor3').show();
            $('#floor4').show();
            $('#floor5').hide();
            $('#floor6').hide();
            $('#floor7').hide();
        }

        if(data == 4){
            $('#floor1').show();
            $('#floor2').show();
            $('#floor3').show();
            $('#floor4').show();
            $('#floor5').show();
            $('#floor6').hide();
            $('#floor7').hide();
        }

        if(data == 5){
            $('#floor1').show();
            $('#floor2').show();
            $('#floor3').show();
            $('#floor4').show();
            $('#floor5').show();
            $('#floor6').show();
            $('#floor7').hide();
        }
        // });

        $("#floor_number").on ('change',  function( e ){
            var data = $('#floor_number').val();

            if(data == 1) {
                $('#floor1').show();
                $('#floor2').show();
                $('#floor3').hide();
                $('#floor4').hide();
                $('#floor5').hide();
                $('#floor6').hide();
                $('#floor7').hide();

            }

            if(data == 2) {
                $('#floor1').show();
                $('#floor2').show();
                $('#floor3').show();
                $('#floor4').hide();
                $('#floor5').hide();
                $('#floor6').hide();
                $('#floor7').hide();
            }

            if(data == 3){
                $('#floor1').show();
                $('#floor2').show();
                $('#floor3').show();
                $('#floor4').show();
                $('#floor5').hide();
                $('#floor6').hide();
                $('#floor7').hide();
            }

            if(data == 4){
                $('#floor1').show();
                $('#floor2').show();
                $('#floor3').show();
                $('#floor4').show();
                $('#floor5').show();
                $('#floor6').hide();
                $('#floor7').hide();
            }

            if(data == 5){
                $('#floor1').show();
                $('#floor2').show();
                $('#floor3').show();
                $('#floor4').show();
                $('#floor5').show();
                $('#floor6').show();
                $('#floor7').hide();
            }
        });


        $(document).ready(function() {
            // Basic
            $('.dropify').dropify();
            // Translated
            $('.dropify-fr').dropify({

            });
            // Used events
            var drEvent = $('#input-file-events').dropify();
            drEvent.on('dropify.beforeClear', function(event, element) {
                return confirm("Do you really want to delete \"" + element.file.name + "\" ?");
            });
            drEvent.on('dropify.afterClear', function(event, element) {
                alert('File deleted');
            });
            drEvent.on('dropify.errors', function(event, element) {
                console.log('Has Errors');
            });
            var drDestroy = $('#input-file-to-destroy').dropify();
            drDestroy = drDestroy.data('dropify')
            $('#toggleDropify').on('click', function(e) {
                e.preventDefault();
                if (drDestroy.isDropified()) {
                    drDestroy.destroy();
                } else {
                    drDestroy.init();
                }
            })
        });

    </script>
@endsection

resources/views/consultancy/index.blade.php
@extends('layouts.app')
@section('css')
	<link href="{{ asset(STATIC_DIR.'plugins/bower_components/custom-select/custom-select.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset(STATIC_DIR.'plugins/bower_components/bootstrap-select/bootstrap-select.min.css') }}" rel="stylesheet" />
@endsection
@section('page_title')
	फाईल
@endsection
@section('right_button')
@stop
@section('content-title')
	<h4>फाईल</h4>
@endsection

@section('content')
	<div class="row">
		<div class="col-md-12">
			<div class="white-box">
				<div class="row">
					<div class="col-md-12">
						<div class="panel">
							<div class="table-responsive">
								<table id="form_id" class="display nowrap dataTable table-bordered">
									<thead>
									<tr>
										<th width="50" class="text-center">#</th>
										<th width="150" class="text-center">दर्ता नं.</th>
										<th class="text-center">जग्गा धनीको नाम थर</th>
										<th class="text-center">ठेगाना</th>
										<th class="text-center">वडा नं</th>
										<th class="text-center">निर्माण किसिम</th>
										<th class="text-center">दर्ता मिति</th>
										<th class="text-center"></th>
									</tr>
									</thead>
									<tbody>
									@if (isset($formData))
										@foreach($formData as $value)
											<tr>
												<td class="text-center">
													{{ $loop->iteration }}
												</td>
												<td class="text-center">
													{{ $value->darta_number }}
												</td>
												<td class="text-center">{{ $value->sambodhan }} {{ $value->field_owner_name }}</td>
												<td class="text-center">{{ $value->field_owner_address }}</td>
												<td class="text-center">{{ $value->landInfo->current_ward_number }}</td>
												<td class="text-center">{{ $value->building_type }}</td>
												<td class="text-center">{{ $value->created_at_nepali }}</td>
												<td class="text-center">
													@if ($value->form_level==6)
														<a href="{{ route('consultancy.get_dpc_form',$value->id) }}" type="button" class="btn btn-info btn-block btn-sm">DPC</a>
													@elseif($value->form_level==11)
														<a href="{{ route('consultancy.get_sampanna_form',$value->id) }}" type="button" class="btn btn-info btn-sm m-r-5">Sampanna</a>
														<a href="{{ route('consultancy.view_housemap',$value->id) }}" type="button" class="btn btn-info btn-sm m-r-5">Change Map</a>
													@else
														<a href="{{ route('consultancy.view_full_form',$value->id) }}" type="button" class="btn btn-info btn-block btn-sm">View</a>
													@endif
												</td>
											</tr>
										@endforeach
									@endif
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	@include('permission.model')
@endsection

@section('scripts')
	<script src="{{ asset(STATIC_DIR.'plugins/bower_components/custom-select/custom-select.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset(STATIC_DIR.'plugins/bower_components/bootstrap-select/bootstrap-select.min.js') }}" type="text/javascript"></script>
	<script>
        jQuery(document).ready(function() {
            // Switchery
            var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
            $('.js-switch').each(function() {
                new Switchery($(this)[0], $(this).data());
            });
            // For select 2
            $(".select2").select2();
            $('.selectpicker').selectpicker();
            //Bootstrap-TouchSpin

            $(document).ready( function () {
                $('#form_id').DataTable({"bSort" : false});
            } );
        });
	</script>
@endsection

resources/views/consultancy/list_rejected.blade.php
@extends('layouts.app')
@section('css')
	<link href="{{ asset(STATIC_DIR.'plugins/bower_components/custom-select/custom-select.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset(STATIC_DIR.'plugins/bower_components/bootstrap-select/bootstrap-select.min.css') }}" rel="stylesheet" />
@endsection
@section('page_title')
	अस्वीकृत फाईल
@endsection
@section('right_button')
@stop
@section('content-title')
	<h4>अस्वीकृत फाईल</h4>
@endsection

@section('content')
	<div class="row">
		<div class="col-md-12">
			<div class="white-box">
				<div class="row">
					<div class="col-md-12">
						<div class="panel">
							<div class="table-responsive">
								<table id="form_id" class="display nowrap dataTable table-bordered">
									<thead>
									<tr>
										<th width="50" class="text-center">S.N.</th>
										<th width="150" class="text-center">दर्ता नं.</th>
										<th class="text-center">जग्गा धनीको नाम थर</th>
										<th class="text-center">ठेगाना</th>
										<th class="text-center">वडा नं</th>
										<th class="text-center">निर्माण किसिम</th>
										<th class="text-center">दर्ता मिति</th>
										<th class="text-center"></th>
									</tr>
									</thead>
									<tbody>
									@if (isset($formData))
										@foreach($formData as $value)
											<tr>
												<td class="text-center">{{ $loop->iteration }}</td>
												<td class="text-center">{{ $value->darta_number }}</td>
												<td class="text-center">{{ $value->sambodhan ?? '' }}&nbsp;{{ $value->field_owner_name ?? '' }}</td>
												<td class="text-center">{{ $value->field_owner_address ?? '' }}</td>
												<td class="text-center">{{ $value->landInfo->current_ward_number ?? '' }}</td>
												<td class="text-center">{{ $value->building_type ?? '' }}</td>
												<td class="text-center">{{ $value->created_at_nepali ?? '' }}</td>
												<td class="text-center">
													<a class="btn btn-warning btn-block btn-sm" data-toggle="modal" data-target="#myModal" >Error</a>
													@if($value->form_level == 6)
														<a href="{{ route('consultancy.rejected.edit_dpcform',$value->id) }}" type="button" class="btn btn-info btn-block btn-sm">Edit DPC</a>
													@elseif($value->form_level == 11)
														<a href="{{ route('consultancy.rejected.edit_sampanna',$value->id) }}" type="button" class="btn btn-info btn-block btn-sm">Edit Sampanna</a>
													@else
														<a href="{{ route('consultancy.rejected.edit_form',$value->id) }}" type="button" class="btn btn-info btn-block btn-sm">Edit</a>
													@endif
												</td>
											
											</tr>
										@endforeach
									@endif
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	@include('consultancy.modal')
	@include('permission.model')
@endsection

@section('scripts')
	<script src="{{ asset(STATIC_DIR.'plugins/bower_components/custom-select/custom-select.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset(STATIC_DIR.'plugins/bower_components/bootstrap-select/bootstrap-select.min.js') }}" type="text/javascript"></script>
	<script>

        jQuery(document).ready(function() {
            // Switchery
            var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
            $('.js-switch').each(function() {
                new Switchery($(this)[0], $(this).data());
            });
            // For select 2
            $(".select2").select2();
            $('.selectpicker').selectpicker();
            //Bootstrap-TouchSpin

            $(document).ready( function () {
                $('#form_id').DataTable({"bSort" : false});
            });
        });
	
	
	</script>
@endsection

resources/views/consultancy/modal.blade.php
<div id="myModal" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">अस्वीकृत गर्नुको कारण</h4> </div>
            <div class="modal-body">
                <p class="text-danger">{{ isset($value->rejected_message) ? $value->rejected_message : 'n/a' }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

{{--to upload dpc_form  signed one.--}}
<div class="modal fade" id="uploadDpc" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('consultancy.uploaddpc') }}" method="post" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="form_id" id="form_id_dpc">
                <input type="hidden" name="action" value="{{$action ?? ''}}">
                
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" >DPC  फाईल अपलोड</h4> </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="dpc_scan" class="control-label">
                            DPC File:
                        </label>
                        <input type="file" name="upload_dpc" id="input-file-now" class="dropify"  accept=".jpeg,.jpg,.png"/>
                        @if($errors->has('dpc_scan'))
                            <span class="text-danger">{{ $errors->first('tippani_scan') }}</span>
                        @endif
                    </div>
                
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-info">Upload</button>
                </div>
            </form>
        </div>
    </div>
</div>

{{--to upload sampanna_form signed one.--}}
<div class="modal fade" id="uploadSampanna" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('consultancy.uploadsampanna') }}" method="post" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="form_id" id="form_id_sampanna">
                <input type="hidden" name="action" value="{{$action ?? ''}}">
                
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" >सम्पन्न  फाईल अपलोड</h4> </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="dpc_scan" class="control-label">
                            सम्पन्न  फाईल :
                        </label>
                        <input type="file" name="upload_sampanna" id="input-file-now" class="dropify"  accept=".jpeg,.jpg,.png"/>
                        @if($errors->has('dpc_scan'))
                            <span class="text-danger">{{ $errors->first('tippani_scan') }}</span>
                        @endif
                    </div>
                
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-info">
                        @if(isset($action))
                            @if($action == 'edit')
                                Update
                            @else
                                Upload
                            @endif
                        @endif
                    
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>