routes/web.php
    Route::post('/view_sandhir', ['uses' => 'AaminController@store_aaminPratibedan' , 'as' => 'store_aaminPratibedan'])->middleware('can:aamin');
    Route::get('/view_aamin_pratibedan/{form_id}', ['uses' => 'AaminController@get_aaminPratibedan' , 'as' =>'view_aamin'])->middleware('can:aamin');

    //to display the rejected files.
    Route::get('/list_rejected', ['uses' => 'AaminController@get_rejected_file' , 'as' =>'list_rejected'])->middleware('can:aamin');

    //to edit the aamin_pratibedan form.
    Route::get('/edit_form/{form_id}', ['uses' => 'AaminController@editAaminPratibedan' , 'as' =>'edit_aaminPratibedan'])->middleware('can:aamin');

    //to store uploaded aamin_pratibedan form
    Route::post('/aamin_pratibedan_upload', ['uses' => 'AaminController@store_aaminPratibedanUpload' , 'as' => 'upload_aaminPratibedan'])->middleware('can:aamin');

    //to view both file after upload amin_pratibedan form.
    Route::get('/view_uploaded_aaminpratibedan/{form_id}', ['uses' => 'AaminController@getUploadedaaminpratibedan' , 'as' =>'view_uploaded_aaminpratibedan'])->middleware('can:aamin');
});

//ENGINEER ROUTE
Route::group(['prefix' =>ROOT_DIR.'engineer', 'middleware' => 'auth', 'as' => 'engineer.'], function () {
    Route::get('/list', ['uses'=>'EngineerController@index','as'=>'index'])->middleware('can:engineer');

    Route::get('/sandhir_suchana/{form_id}', ['uses'=>'EngineerController@sandhir_suchana','as'=>'sandhir_suchana'])->middleware('can:engineer');

    //route to view rajashow form
    Route::get('/view_rajashow/{form_id}', ['uses'=>'EngineerController@view_rajashow_form','as'=>'view_rajashow'])->middleware('can:engineer');
    Route::post('/reject_form', ['uses'=>'EngineerController@reject_form','as'=>'rejectForm'])->middleware('can:engineer');
    Route::post('/sandhir_upload', ['uses'=>'EngineerController@sandhir_upload','as'=>'sandhir_upload'])->middleware('can:engineer');
    Route::get('/view_sandhir/{form_id}', ['uses'=>'EngineerController@view_sandhir','as'=>'view_sandhir'])->middleware('can:engineer');

    //to find which route to choose consultancy form or aamin_pratibedan form.
    Route::get('/check_form/{form_id}', ['uses'=>'EngineerController@check_form_level','as'=>'check_form'])->middleware('can:engineer');
    Route::get('/tippani_adesh/{form_id}', ['uses'=>'EngineerController@tippani_adesh','as'=>'tippani_adesh'])->middleware('can:engineer');

    //route to store tippani and esthae scan
    Route::post('/tippani', ['uses' => 'EngineerController@store_tippani', 'as'=>'tippani_upload'])->middleware('can:engineer');
    Route::get('/upload/tippani_adesh/{form_id}', ['uses'=>'EngineerController@get_uploaded_tippani_adesh','as'=>'uploaded_tippani_adesh'])->middleware('can:engineer');
    //dpc
    Route::get('/get_print_dpc', ['uses'=>'EngineerController@get_print_dpc','as'=>'get_print_dpc'])->middleware('can:engineer');
    Route::post('/dpc_upload', ['uses' => 'EngineerController@store_dpc', 'as'=>'dpc_upload'])->middleware('can:engineer');
    Route::get('/dpc/uploaded_dpc/{form_id}', ['uses'=>'EngineerController@get_uploaded_dpc','as'=>'uploaded_dpc'])->middleware('can:engineer');

    //sampanna
    Route::get('/get_print_sampanna/{form_id}', ['uses'=>'EngineerController@get_print_sampanna','as'=>'get_print_sampanna'])->middleware('can:engineer');
    Route::post('/proceed_sampanna', ['uses' => 'EngineerController@proceed_sampanna', 'as'=>'proceed_sampanna'])->middleware('can:engineer');
    Route::get('/sampanna/display_file/{form_id}', ['uses'=>'EngineerController@get_uploaded_sampanna','as'=>'view_sampanna'])->middleware('can:engineer');
    Route::get('/skipdate/{form_id}', ['uses'=>'EngineerController@skipdate','as'=>'skipdate'])->middleware('can:engineer');
});

// MAIN ENGINEER ROUTE
Route::group(['prefix' =>ROOT_DIR.'mainengineer', 'middleware' => 'auth', 'as' => 'mainengineer.'], function () {
    Route::get('/list', ['uses'=>'MainengineerController@index','as'=>'index'])->middleware('can:main-engineer');
    Route::get('/dpc/{form_id}', ['uses'=>'MainengineerController@get_dpc','as'=>'get_dpc'])->middleware('can:main-engineer');
    Route::get('/dpc_scan/{form_id}', ['uses'=>'MainengineerController@get_dpc_scan','as'=>'get_dpc_scan'])->middleware('can:main-engineer');
    Route::get('/proceed/{form_id}', ['uses'=>'MainengineerController@proceed','as'=>'proceed'])->middleware('can:main-engineer');
    Route::get('/proceeddpc/{form_id}', ['uses'=>'MainengineerController@get_proceeddpc','as'=>'proceeddpc'])->middleware('can:main-engineer');
    //to view sampanna
    Route::get('/view_sampanna/{form_id}', ['uses'=>'MainengineerController@get_sampanna','as'=>'view_sampanna'])->middleware('can:main-engineer');
    Route::get('/proceed_sampanna/{form_id}', ['uses'=>'MainengineerController@proceed_sampanna','as'=>'proceed_sampanna'])->middleware('can:main-engineer');
});

// SUB ENGINEER ROUTE
Route::group(['prefix' =>ROOT_DIR.'subengineer', 'middleware' => 'auth', 'as' => 'subengineer.'], function () {
    Route::get('/list', ['uses'=>'SubengineerController@index','as'=>'index'])->middleware('can:sub-engineer');
    Route::get('/view_aamin_pratibaden/{form_id}', ['uses'=>'SubengineerController@get_aamin_pratibaden','as'=>'get_aamin_pratibaden'])->middleware('can:sub-engineer');
    Route::get('/rajashow/{form_id}', ['uses'=>'SubengineerController@get_rajashow','as'=>'rajashow'])->middleware('can:sub-engineer');
    Route::post('/rajashow/save', ['uses'=>'SubengineerController@post_rajashow','as'=>'rajashow.store'])->middleware('can:sub-engineer');
    Route::get('/rajashow/view/{form_id}', ['uses'=>'SubengineerController@display_rajashow','as'=>'rajashow.view'])->middleware('can:sub-engineer');
    Route::post('/rejectForm', ['uses'=>'SubengineerController@reject_form','as'=>'rejectForm'])->middleware('can:sub-engineer');
    //after rajashow print.
    Route::post('/rejashow/upload', ['uses'=>'SubengineerController@upload_rajashow_print','as'=>'rajashow.upload'])->middleware('can:sub-engineer');
    Route::get('/rajashow/displayrajashow/{form_id}',['uses' => 'SubengineerController@get_uploaded_rajashow', 'as' => 'displayrajashow'])->middleware('can:sub-engineer');

    //dpc route
    Route::get('/view_dpc/{form_id}', ['uses'=>'SubengineerController@get_dpc','as'=>'get_dpc'])->middleware('can:sub-engineer');
    Route::post('/post_proceeddpc', ['uses'=>'SubengineerController@post_proceeddpc','as'=>'post_proceeddpc'])->middleware('can:sub-engineer');
    Route::get('/view_proceeddpc/{form_id}',['uses' => 'Subengineercontroller@get_proceeddpc', 'as' => 'view_proceeddpc'])->middleware('can:sub-engineer');

    //route for reject dpc modal
    Route::post('/rejectdpc', ['uses'=>'SubengineerController@post_rejectdpc','as'=>'rejectdpc'])->middleware('can:sub-engineer');

    //route for upload for superstructure certificate
    Route::get('/view_upload_superstructure/{form_id}', ['uses'=>'SubengineerController@get_upload_superstructure','as'=>'view_upload_superstructure'])->middleware('can:sub-engineer');
    Route::post('/superstructure', ['uses'=>'SubengineerController@post_superstructure','as'=>'superstructure'])->middleware('can:sub-engineer');
    Route::get('/superstructure/view_uploaded/{form_id}', ['uses'=>'SubengineerController@get_uploaded_superstructure','as'=>'view_uploaded'])->middleware('can:sub-engineer');

    //route for viewing and rejecting  for sampanna_form
    Route::get('/view_sampanna/{form_id}', ['uses'=>'SubengineerController@get_sampanna','as'=>'view_sampanna'])->middleware('can:sub-engineer');
    Route::get('/proceed_sampanna/{form_id}', ['uses'=>'SubengineerController@get_proceedSampanna','as'=>'proceed_sampanna'])->middleware('can:sub-engineer');
    Route::post('/rejectsampanna', ['uses'=>'SubengineerController@post_rejectsampanna','as'=>'rejectsampanna'])->middleware('can:sub-engineer');
    Route::get('/view_rejectsampanna/{form_id}', ['uses'=>'SubengineerController@get_rejectsampanna','as'=>'view_rejectsampanna'])->middleware('can:sub-engineer');
    Route::get('/upload_sampanna/{form_id}', ['uses'=>'SubengineerController@get_upload_sampanna','as'=>'get_upload_sampanna'])->middleware('can:sub-engineer');
    Route::post('/upload_sampanna_file', ['uses'=>'SubengineerController@post_upload_sampanna','as'=>'post_upload_sampanna'])->middleware('can:sub-engineer');
    Route::get('/view_sampanna_file/{form_id}', ['uses'=>'SubengineerController@view_sampanna_file','as'=>'view_sampanna_file']);
});

// ADMINISTRATOR ROUTE
Route::group(['prefix' =>ROOT_DIR.'administration', 'middleware' => ['auth','can:administration'], 'as' => 'administration.'], function () {
    Route::get('/get_files', ['uses'=>'AdministrationController@get_files','as'=>'get_files']);
    Route::get('/get_edit/{form_id}', ['uses'=>'AdministrationController@get_edit','as'=>'get_edit']);

    //to edit form
    Route::get('/edit_form/{form_id}', ['uses'=>'ConsultancyController@get_edit_form','as'=>'edit_form_administration']);
    Route::post('/edit_form', ['uses'=>'ConsultancyController@post_edit_form','as'=>'post_edit_form']);

    //edit rajashow
    Route::get('/rajashow/{form_id}', ['uses'=>'SubengineerController@get_rajashow','as'=>'rajashow'])->middleware('can:administration');
    Route::post('/rajashow/save', ['uses'=>'SubengineerController@post_rajashow','as'=>'rajashow.store'])->middleware('can:administration');

    //edit dpc
    Route::get('/edit_dpcform/{form_id}', ['uses'=>'ConsultancyController@get_edit_dpcform','as'=>'edit_dpcform'])->middleware('can:administration');
    Route::post('/dpc', ['uses'=>'ConsultancyController@post_dpc_form','as'=>'post_dpc_form'])->middleware('can:administration');

    //edit aamin pratibedan
    Route::get('/edit_aamin_form/{form_id}', ['uses' => 'AaminController@editAaminPratibedan' , 'as' =>'edit_aaminPratibedan'])->middleware('can:administration');

resources/views/sub_engineer/index.blade.php
@extends('layouts.app')
@section('css')
	<link href="{{ asset(STATIC_DIR.'plugins/bower_components/custom-select/custom-select.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset(STATIC_DIR.'plugins/bower_components/bootstrap-select/bootstrap-select.min.css') }}" rel="stylesheet" />
@endsection
@section('page_title')
	Files listing
@endsection
@section('right_button')
@stop
@section('content-title')
	<h4>फाईल खोज्नुहोस</h4>
@endsection

@section('content')
	<div class="row">
		<div class="col-md-12">
			<div class="white-box">
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<form action="{{ route('subengineer.index') }}" method="get">
							@csrf
							<div class="row">
								<div class="col-md-3">
									<strong>फाईल खोज्नुहोस</strong>
								</div>
								<div class="col-md-7">
									<select class="form-control select2" name="ward_number">
										<option value="">वडा नं * </option>
										@if (isset($ward))
											@foreach($ward as $value)
												<option value="{{ $value->ward_number }}">{{ $value->ward_number }}</option>
											@endforeach
										@endif
									</select>
								</div>
								<div class="col-md-2">
									<button type="submit" class="btn btn-default">Search</button>
								</div>
							</div>
						</form>
					</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-md-12">
						<div class="panel">
							@if(isset($ward_number))
								<div class="panel-heading">वडा नं. : {{ $ward_number }} का फाईल</div>
							@else
								<div class="panel-heading">वडा नं. चयन गर्नुहोस</div>
							@endif
							<div class="table-responsive">
								<table id="form_id" class="display nowrap dataTable table-bordered">
									<thead>
									<tr>
										<th width="50" class="text-center">#</th>
										<th width="150" class="text-center">दर्ता नं.</th>
										<th class="text-center">जग्गा धनीको नाम थर</th>
										<th class="text-center">ठेगाना</th>
										<th class="text-center">वडा नं</th>
										<th class="text-center">निर्माण किसिम</th>
										<th class="text-center">दर्ता मिति</th>
										<th class="text-center"></th>
									</tr>
									</thead>
									<tbody>
									@if (isset($files))
										@foreach($files as $value)
											<tr>
												<td class="text-center">{{ $loop->iteration }}</td>
												<td class="text-center">{{ $value->darta_number }}</td>
												<td class="text-center">{{ $value->sambodhan }} {{ $value->field_owner_name }}</td>
												<td class="text-center">{{ $value->field_owner_address }}</td>
												<td class="text-center">{{ $value->current_ward_number }}</td>
												<td class="text-center">{{ $value->building_type }}</td>
												<td class="text-center">{{ $value->created_at_nepali }}</td>
												<td class="text-center">
													@if ($value->form_level==7)
														<a href="{{ route('subengineer.get_dpc',$value->id) }}" type="button" class="btn btn-info btn-block btn-sm"> DPC</a>
													@elseif($value->form_level == 3)
														<a href="{{ route('subengineer.get_aamin_pratibaden',$value->id) }}" type="button" class="btn btn-info btn-block btn-sm">Proceed</a>
													@elseif($value->form_level == 4)
														<a href="{{ route('subengineer.rajashow.view',$value->id) }}" type="button" class="btn btn-info btn-block btn-sm">Upload Rajashow</a>
													@elseif($value->form_level == 10)
														<a href="{{ route('subengineer.view_upload_superstructure',$value->id) }}" class="btn btn-info btn-block btn-sm">Superstructure</a>
													@elseif($value->form_level == 12)
														<a href="{{ route('subengineer.view_sampanna',$value->id) }}" class="btn btn-info btn-block btn-sm">Sampanna</a>
													@elseif($value->form_level == 15)
														<a href="{{ route('subengineer.get_upload_sampanna',$value->id) }}" class="btn btn-info btn-block btn-sm">Upload sampanna</a>
													@elseif($value->is_completed == 1)
														<a href="{{ route('subengineer.view_sampanna_file',$value->id) }}" class="btn btn-info btn-block btn-sm">Completed/a>

													@endif

												</td>
											</tr>
										@endforeach
									@endif
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	@include('permission.model')
@endsection

@section('scripts')
	<script src="{{ asset(STATIC_DIR.'plugins/bower_components/custom-select/custom-select.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset(STATIC_DIR.'plugins/bower_components/bootstrap-select/bootstrap-select.min.js') }}" type="text/javascript"></script>
	<script>
		jQuery(document).ready(function() {
			// Switchery
			var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
			$('.js-switch').each(function() {
				new Switchery($(this)[0], $(this).data());
			});
			// For select 2
			$(".select2").select2();
			$('.selectpicker').selectpicker();
			//Bootstrap-TouchSpin

			$(document).ready( function () {
				$('#form_id').DataTable({"bSort" : false});
			} );
		});
	</script>
@endsection

resources/views/sub_engineer/modal.blade.php
<div class="modal fade" id="reject" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('subengineer.rejectForm') }}" method="post">
                @csrf
                <input type="hidden" name="form_id" id="form_id">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel1">अस्वीकृत गर्नुहोस </h4> </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="message-text" class="control-label">अस्वीकृत गर्ने कारण </label>
                        <textarea name="rejected_message" class="form-control" rows="10" id="message-text1" placeholder="अस्वीकृत गर्ने कारण लेखनुहोस|"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-info">Reject</button>
                </div>
            </form>
        </div>
    </div>
</div>


{{--file upload --}}
<div class="modal fade" id="uploadRajashow" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('subengineer.rajashow.upload') }}" method="post" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="form_id" id="form_id_rejashow">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel1">रजशोव  फाईल अपलोड</h4> </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="other_document_2" class="control-label">
                            रजशोव  फाईल अपलोड गर्नुहोस|
                        </label>
                        <input type="file" name="rajashow_scan" id="input-file-now" class="dropify"  accept=".jpeg,.jpg,.png"/>
                        @if($errors->has('rajashow_scan'))
                            <span class="text-danger">{{ $errors->first('rajashow_scan') }}</span>
                        @endif
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-info">Upload</button>
                </div>
            </form>
        </div>
    </div>
</div>


{{--reject modal for dpc form--}}
<div class="modal fade" id="rejectdpc" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('subengineer.rejectdpc') }}" method="post">
                @csrf
                <input type="hidden" name="form_id" id="dpc_form_id">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel1">अस्वीकृत गर्नुहोस </h4> </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="message-text" class="control-label">अस्वीकृत गर्ने कारण </label>
                        <textarea name="rejected_message" class="form-control" rows="10" id="message-text1" placeholder="अस्वीकृत गर्ने कारण लेखनुहोस|"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-info">Reject</button>
                </div>
            </form>
        </div>
    </div>
</div>

{{--reject modal for sampanna form--}}
<div class="modal fade" id="rejectsampanna" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{{ route('subengineer.rejectsampanna') }}" method="post">
                @csrf
                <input type="hidden" name="form_id" id="sampanna_form_id">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel1">अस्वीकृत गर्नुहोस </h4> </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="message-text" class="control-label">अस्वीकृत गर्ने कारण </label>
                        <textarea name="rejected_message" class="form-control" rows="10" id="message-text1" placeholder="अस्वीकृत गर्ने कारण लेखनुहोस|"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-info">Reject</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/sub_engineer/upload_sampanna.blade.php
@extends('layouts.app')
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'plugins/bower_components/dropify/dist/css/dropify.min.css') }}">
@endsection
@section('page_title')
    Files listing
@endsection
@section('right_button')
@stop
@section('content-title')
    <h4>फाईल खोज्नुहोस</h4>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="white-box">
                <div class="row">
                    <div class="col-md-12">
                        <form action="{{ route('subengineer.post_upload_sampanna') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <input type="hidden" name="form_id" value="{{$formData->id}}">

                            {{--<div class="form-group">
                                <label for="sampanna_form" class="control-label">
                                    Sampanna form फाईल अपलोड गर्नुहोस।
                                </label>

                                <input type="file" name="sampanna_form" id="input-file-now" class="dropify"  accept=".pdf,.jpeg,.jpg,.png" required="" />
                                @if($errors->has('sampanna_form'))
                                    <span class="text-danger">{{ $errors->first('sampanna_form') }}</span>
                                @endif
                            </div>--}}

                            <div class="form-group">
                                <label for="sampanna_tippani" class="control-label">
                                    Sampanna tippani फाईल अपलोड गर्नुहोस।
                                </label>

                                <input type="file" name="sampanna_tippani" id="input-file-now" class="dropify"  accept=".jpeg,.jpg,.png" required="" />
                                @if($errors->has('sampanna_tippani'))
                                    <span class="text-danger">{{ $errors->first('sampanna_tippani') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="sampanna_certificate" class="control-label">
                                    Sampanna certificate फाईल अपलोड गर्नुहोस।
                                </label>

                                <input type="file" name="sampanna_certificate" id="input-file-now" class="dropify"  accept=".jpeg,.jpg,.png" required="" />
                                @if($errors->has('sampanna_certificate'))
                                    <span class="text-danger">{{ $errors->first('sampanna_certificate') }}</span>
                                @endif
                            </div>

                            <div class="row pull-right">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary">Upload</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    @include('permission.model')
@endsection

@section('scripts')
    <script src="{{ asset(STATIC_DIR.'plugins/bower_components/dropify/dist/js/dropify.min.js')}}"></script>

    <script>
        $(document).ready(function() {
            $('.dropify').dropify();

        });
    </script>
@endsection

resources/views/sub_engineer/upload_superstructure.blade.php
@extends('layouts.app')
@section('css')
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'plugins/bower_components/dropify/dist/css/dropify.min.css') }}">
@endsection
@section('page_title')
    Files listing
@endsection
@section('right_button')
@stop
@section('content-title')
    <h4>फाईल खोज्नुहोस</h4>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="white-box">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <form action="{{ route('subengineer.superstructure') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <input type="hidden" name="form_id" value="{{$form_id}}">

                            <div class="form-group">
                                <label for="superstructure_certificate_scan" class="control-label">
                                    Superstructure Certificate  फाईल अपलोड गर्नुहोस|
                                </label>

                                <input type="file" name="superstructure_certificate_scan" id="input-file-now" class="dropify"  accept=".jpeg,.jpg,.png"/>
                                @if($errors->has('superstructure_certificate_scan'))
                                    <span class="text-danger">{{ $errors->first('superstructure_certificate_scan') }}</span>
                                @endif
                            </div>

                            <div class="row col-md-3 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">Upload</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    @include('permission.model')
@endsection

@section('scripts')
    <script src="{{ asset(STATIC_DIR.'plugins/bower_components/dropify/dist/js/dropify.min.js')}}"></script>

    <script>
        $(document).ready(function() {
            $('.dropify').dropify();

        });
    </script>
@endsection