routes/web.php
    Route::post('/view_sandhir', ['uses' => 'AaminController@store_aaminPratibedan' , 'as' => 'store_aaminPratibedan'])->middleware('can:aamin');
    Route::get('/view_aamin_pratibedan/{form_id}', ['uses' => 'AaminController@get_aaminPratibedan' , 'as' =>'view_aamin'])->middleware('can:aamin');

    //to display the rejected files.
    Route::get('/list_rejected', ['uses' => 'AaminController@get_rejected_file' , 'as' =>'list_rejected'])->middleware('can:aamin');

    //to edit the aamin_pratibedan form.
    Route::get('/edit_form/{form_id}', ['uses' => 'AaminController@editAaminPratibedan' , 'as' =>'edit_aaminPratibedan'])->middleware('can:aamin');

    //to store uploaded aamin_pratibedan form
    Route::post('/aamin_pratibedan_upload', ['uses' => 'AaminController@store_aaminPratibedanUpload' , 'as' => 'upload_aaminPratibedan'])->middleware('can:aamin');

    //to view both file after upload amin_pratibedan form.
    Route::get('/view_uploaded_aaminpratibedan/{form_id}', ['uses' => 'AaminController@getUploadedaaminpratibedan' , 'as' =>'view_uploaded_aaminpratibedan'])->middleware('can:aamin');
});

//ENGINEER ROUTE
Route::group(['prefix' =>ROOT_DIR.'engineer', 'middleware' => 'auth', 'as' => 'engineer.'], function () {
    Route::get('/list', ['uses'=>'EngineerController@index','as'=>'index'])->middleware('can:engineer');

    Route::get('/sandhir_suchana/{form_id}', ['uses'=>'EngineerController@sandhir_suchana','as'=>'sandhir_suchana'])->middleware('can:engineer');

    //route to view rajashow form
    Route::get('/view_rajashow/{form_id}', ['uses'=>'EngineerController@view_rajashow_form','as'=>'view_rajashow'])->middleware('can:engineer');
    Route::post('/reject_form', ['uses'=>'EngineerController@reject_form','as'=>'rejectForm'])->middleware('can:engineer');
    Route::post('/sandhir_upload', ['uses'=>'EngineerController@sandhir_upload','as'=>'sandhir_upload'])->middleware('can:engineer');
    Route::get('/view_sandhir/{form_id}', ['uses'=>'EngineerController@view_sandhir','as'=>'view_sandhir'])->middleware('can:engineer');

    //to find which route to choose consultancy form or aamin_pratibedan form.
    Route::get('/check_form/{form_id}', ['uses'=>'EngineerController@check_form_level','as'=>'check_form'])->middleware('can:engineer');
    Route::get('/tippani_adesh/{form_id}', ['uses'=>'EngineerController@tippani_adesh','as'=>'tippani_adesh'])->middleware('can:engineer');

    //route to store tippani and esthae scan
    Route::post('/tippani', ['uses' => 'EngineerController@store_tippani', 'as'=>'tippani_upload'])->middleware('can:engineer');
    Route::get('/upload/tippani_adesh/{form_id}', ['uses'=>'EngineerController@get_uploaded_tippani_adesh','as'=>'uploaded_tippani_adesh'])->middleware('can:engineer');
    //dpc
    Route::get('/get_print_dpc', ['uses'=>'EngineerController@get_print_dpc','as'=>'get_print_dpc'])->middleware('can:engineer');
    Route::post('/dpc_upload', ['uses' => 'EngineerController@store_dpc', 'as'=>'dpc_upload'])->middleware('can:engineer');
    Route::get('/dpc/uploaded_dpc/{form_id}', ['uses'=>'EngineerController@get_uploaded_dpc','as'=>'uploaded_dpc'])->middleware('can:engineer');

    //sampanna
    Route::get('/get_print_sampanna/{form_id}', ['uses'=>'EngineerController@get_print_sampanna','as'=>'get_print_sampanna'])->middleware('can:engineer');
    Route::post('/proceed_sampanna', ['uses' => 'EngineerController@proceed_sampanna', 'as'=>'proceed_sampanna'])->middleware('can:engineer');
    Route::get('/sampanna/display_file/{form_id}', ['uses'=>'EngineerController@get_uploaded_sampanna','as'=>'view_sampanna'])->middleware('can:engineer');
    Route::get('/skipdate/{form_id}', ['uses'=>'EngineerController@skipdate','as'=>'skipdate'])->middleware('can:engineer');
});

// MAIN ENGINEER ROUTE
Route::group(['prefix' =>ROOT_DIR.'mainengineer', 'middleware' => 'auth', 'as' => 'mainengineer.'], function () {
    Route::get('/list', ['uses'=>'MainengineerController@index','as'=>'index'])->middleware('can:main-engineer');
    Route::get('/dpc/{form_id}', ['uses'=>'MainengineerController@get_dpc','as'=>'get_dpc'])->middleware('can:main-engineer');
    Route::get('/dpc_scan/{form_id}', ['uses'=>'MainengineerController@get_dpc_scan','as'=>'get_dpc_scan'])->middleware('can:main-engineer');
    Route::get('/proceed/{form_id}', ['uses'=>'MainengineerController@proceed','as'=>'proceed'])->middleware('can:main-engineer');
    Route::get('/proceeddpc/{form_id}', ['uses'=>'MainengineerController@get_proceeddpc','as'=>'proceeddpc'])->middleware('can:main-engineer');
    //to view sampanna
    Route::get('/view_sampanna/{form_id}', ['uses'=>'MainengineerController@get_sampanna','as'=>'view_sampanna'])->middleware('can:main-engineer');
    Route::get('/proceed_sampanna/{form_id}', ['uses'=>'MainengineerController@proceed_sampanna','as'=>'proceed_sampanna'])->middleware('can:main-engineer');
});

// SUB ENGINEER ROUTE
Route::group(['prefix' =>ROOT_DIR.'subengineer', 'middleware' => 'auth', 'as' => 'subengineer.'], function () {
    Route::get('/list', ['uses'=>'SubengineerController@index','as'=>'index'])->middleware('can:sub-engineer');
    Route::get('/view_aamin_pratibaden/{form_id}', ['uses'=>'SubengineerController@get_aamin_pratibaden','as'=>'get_aamin_pratibaden'])->middleware('can:sub-engineer');
    Route::get('/rajashow/{form_id}', ['uses'=>'SubengineerController@get_rajashow','as'=>'rajashow'])->middleware('can:sub-engineer');
    Route::post('/rajashow/save', ['uses'=>'SubengineerController@post_rajashow','as'=>'rajashow.store'])->middleware('can:sub-engineer');
    Route::get('/rajashow/view/{form_id}', ['uses'=>'SubengineerController@display_rajashow','as'=>'rajashow.view'])->middleware('can:sub-engineer');
    Route::post('/rejectForm', ['uses'=>'SubengineerController@reject_form','as'=>'rejectForm'])->middleware('can:sub-engineer');
    //after rajashow print.
    Route::post('/rejashow/upload', ['uses'=>'SubengineerController@upload_rajashow_print','as'=>'rajashow.upload'])->middleware('can:sub-engineer');
    Route::get('/rajashow/displayrajashow/{form_id}',['uses' => 'SubengineerController@get_uploaded_rajashow', 'as' => 'displayrajashow'])->middleware('can:sub-engineer');

    //dpc route
    Route::get('/view_dpc/{form_id}', ['uses'=>'SubengineerController@get_dpc','as'=>'get_dpc'])->middleware('can:sub-engineer');
    Route::post('/post_proceeddpc', ['uses'=>'SubengineerController@post_proceeddpc','as'=>'post_proceeddpc'])->middleware('can:sub-engineer');
    Route::get('/view_proceeddpc/{form_id}',['uses' => 'Subengineercontroller@get_proceeddpc', 'as' => 'view_proceeddpc'])->middleware('can:sub-engineer');

    //route for reject dpc modal
    Route::post('/rejectdpc', ['uses'=>'SubengineerController@post_rejectdpc','as'=>'rejectdpc'])->middleware('can:sub-engineer');

    //route for upload for superstructure certificate
    Route::get('/view_upload_superstructure/{form_id}', ['uses'=>'SubengineerController@get_upload_superstructure','as'=>'view_upload_superstructure'])->middleware('can:sub-engineer');
    Route::post('/superstructure', ['uses'=>'SubengineerController@post_superstructure','as'=>'superstructure'])->middleware('can:sub-engineer');
    Route::get('/superstructure/view_uploaded/{form_id}', ['uses'=>'SubengineerController@get_uploaded_superstructure','as'=>'view_uploaded'])->middleware('can:sub-engineer');

    //route for viewing and rejecting  for sampanna_form
    Route::get('/view_sampanna/{form_id}', ['uses'=>'SubengineerController@get_sampanna','as'=>'view_sampanna'])->middleware('can:sub-engineer');
    Route::get('/proceed_sampanna/{form_id}', ['uses'=>'SubengineerController@get_proceedSampanna','as'=>'proceed_sampanna'])->middleware('can:sub-engineer');
    Route::post('/rejectsampanna', ['uses'=>'SubengineerController@post_rejectsampanna','as'=>'rejectsampanna'])->middleware('can:sub-engineer');
    Route::get('/view_rejectsampanna/{form_id}', ['uses'=>'SubengineerController@get_rejectsampanna','as'=>'view_rejectsampanna'])->middleware('can:sub-engineer');
    Route::get('/upload_sampanna/{form_id}', ['uses'=>'SubengineerController@get_upload_sampanna','as'=>'get_upload_sampanna'])->middleware('can:sub-engineer');
    Route::post('/upload_sampanna_file', ['uses'=>'SubengineerController@post_upload_sampanna','as'=>'post_upload_sampanna'])->middleware('can:sub-engineer');
    Route::get('/view_sampanna_file/{form_id}', ['uses'=>'SubengineerController@view_sampanna_file','as'=>'view_sampanna_file']);
});

// ADMINISTRATOR ROUTE
Route::group(['prefix' =>ROOT_DIR.'administration', 'middleware' => ['auth','can:administration'], 'as' => 'administration.'], function () {
    Route::get('/get_files', ['uses'=>'AdministrationController@get_files','as'=>'get_files']);
    Route::get('/get_edit/{form_id}', ['uses'=>'AdministrationController@get_edit','as'=>'get_edit']);

    //to edit form
    Route::get('/edit_form/{form_id}', ['uses'=>'ConsultancyController@get_edit_form','as'=>'edit_form_administration']);
    Route::post('/edit_form', ['uses'=>'ConsultancyController@post_edit_form','as'=>'post_edit_form']);

    //edit rajashow
    Route::get('/rajashow/{form_id}', ['uses'=>'SubengineerController@get_rajashow','as'=>'rajashow'])->middleware('can:administration');
    Route::post('/rajashow/save', ['uses'=>'SubengineerController@post_rajashow','as'=>'rajashow.store'])->middleware('can:administration');

    //edit dpc
    Route::get('/edit_dpcform/{form_id}', ['uses'=>'ConsultancyController@get_edit_dpcform','as'=>'edit_dpcform'])->middleware('can:administration');
    Route::post('/dpc', ['uses'=>'ConsultancyController@post_dpc_form','as'=>'post_dpc_form'])->middleware('can:administration');

    //edit aamin pratibedan
    Route::get('/edit_aamin_form/{form_id}', ['uses' => 'AaminController@editAaminPratibedan' , 'as' =>'edit_aaminPratibedan'])->middleware('can:administration');

resources/views/administrator/editmenu.blade.php
@extends('layouts.app')
@section('css')
@endsection
@section('page_title')
    File Edit
@endsection
@section('right_button')
@stop
@section('content-title')File Edit @endsection
@section('content')
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Name : {{ $files->sambodhan }} {{ $files->field_owner_name }} <span class="label label-primary"> {{ $files->darta_number }}</span>
                    <a href="{{ route('administration.get_files') }}" class="btn btn-info pull-right"><i class="fa fa-arrow-circle-left"></i>&nbsp;Back</a>
                </div>
                <div class="panel-wrapper collapse in">
                    <div class="panel-body">
                        <p><strong>Proceeded To : </strong> <span class="label label-primary">{{ $files->proceeded_to }}</span></p>
                        <p><strong>Building Type : </strong> {{ $files->building_type }}</p>
                        <p><strong>Address : </strong> {{ $files->field_owner_address }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row" >
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-wrapper collapse in">
                    <div class="panel-body text-center">
                        <h3>Consultancy Form</h3>
                        <a href="{{ route('administration.edit_form_administration',$form_id.'?token=administration') }}" class="btn btn-success m-t-10">Edit</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-wrapper collapse in">
                    <div class="panel-body text-center">
                        <h3>Rajashow</h3>
                        <a href="{{ route('administration.rajashow',$form_id.'?token=administration') }}" class="btn btn-success m-t-10">Edit</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-wrapper collapse in">
                    <div class="panel-body text-center">
                        <h3>DPC</h3>
                        <a href="{{ route('administration.edit_dpcform',$form_id.'?token=administration') }}" class="btn btn-success m-t-10">Edit</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-wrapper collapse in">
                    <div class="panel-body text-center">
                        <h3>Amin Pratibedan Form</h3>
                        <a href="{{route('administration.edit_aaminPratibedan',$form_id.'?token=administration')}}" class="btn btn-success m-t-10">Edit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset(STATIC_DIR.'plugins/bower_components/custom-select/custom-select.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset(STATIC_DIR.'plugins/bower_components/bootstrap-select/bootstrap-select.min.js') }}" type="text/javascript"></script>
    <script>
        jQuery(document).ready(function() {
            // Switchery
            var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
            $('.js-switch').each(function() {
                new Switchery($(this)[0], $(this).data());
            });
            // For select 2
            $(".select2").select2();
            $('.selectpicker').selectpicker();
            //Bootstrap-TouchSpin

        });
    </script>
@endsection

resources/views/administrator/index.blade.php
@extends('layouts.app')
@section('css')
	<link rel="stylesheet" type="text/css" href="{{ asset(STATIC_DIR.'jquery.dataTables.css') }}">
@endsection
@section('page_title')
	फाईल
@endsection
@section('right_button')
@stop
@section('content-title')
	<h2>
		फाईल
	</h2>
@endsection

@section('content')
	<div class="row">
		<div class="col-md-12">
			<div class="white-box">
				<div class="row">
					<div class="col-md-12">
						<div class="panel">
							<div class="table-responsive">
								<table id ="form_id" class="table table-hover manage-u-table" >
									<thead>
									<tr>
										<th width="150" class="text-center">S.N.</th>
										<th width="150" class="text-center">दर्ता नं.</th>
										<th>जग्गा धनीको नाम थर</th>
										<th>ठेगाना</th>
										<th>वडा नं</th>
										<th>निर्माण किसिम</th>
										<th>दर्ता मिति</th>
										<th></th>
									</tr>
									</thead>
									<tbody>
									@if (isset($files))
										@foreach($files as $value)
									<tr>
										<td class="text-center">{{ $loop->iteration }}</td>
										<td class="text-center">{{ $value->darta_number }}</td>
										<td>{{ $value->sambodhan }}&nbsp;{{ $value->field_owner_name }}</td>
										<td>{{ $value->field_owner_address }}</td>
										<td>{{ $value->landInfo->current_ward_number }}</td>
										<td>{{ $value->building_type }}</td>
										<td>{{ $value->created_at_nepali }}</td>
										<td>
											<a href="{{ route('administration.get_edit',$value->id) }}" type="button" class="btn btn-link btn-sm m-r-5">Edit File</a>
                                        </td>
									</tr>
										@endforeach
										@endif
										
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	

@endsection

@section('scripts')
	<script type="text/javascript" charset="utf8" src="{{ asset(STATIC_DIR.'jquery.dataTables.js') }}"></script>
	<script src="{{ asset(STATIC_DIR.'plugins/bower_components/custom-select/custom-select.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset(STATIC_DIR.'plugins/bower_components/bootstrap-select/bootstrap-select.min.js') }}" type="text/javascript"></script>
    <script>
        jQuery(document).ready(function() {
            // Switchery
            var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
            $('.js-switch').each(function() {
                new Switchery($(this)[0], $(this).data());
            });
            // For select 2
            $(".select2").select2();
            $('.selectpicker').selectpicker();
            //Bootstrap-TouchSpin

        });

        $(document).ready( function () {
            $('#form_id').DataTable();
        } );

    </script>
@endsection