routes/web.php
<?php

//defines
//use Illuminate\Routing\Route;

if(!defined('STATIC_DIR')) define('STATIC_DIR','public/');
if(!defined('ROOT_DIR')) define('ROOT_DIR','');
if(!defined('ROOT_DIR_NAME')) define('ROOT_DIR_NAME','');
if(!defined('DEFAULT_USER')) define('DEFAULT_USER','');
if(!defined('LOGO_DARK')) define('LOGO_DARK','assets/icons/delta-dark.png');
if(!defined('LOGO_WHITE')) define('LOGO_WHITE','assets/icons/delta-white.png');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// BASE ROUTES
Route::get('/', 'HomeController@index')->name('home');
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');

Route::get('/profile/{status?}', ['uses'=>'ProfileController@get_profile','as'=>'profile']);
Route::post('/update/profile', ['uses'=>'ProfileController@post_profile','as'=>'update_profile']);

Route::group(['prefix' =>ROOT_DIR.'user', 'middleware' => ['auth','can:administration'], 'as' => 'user.'], function () {
    Route::get('/register', ['uses'=>'Auth\RegisterController@showRegistrationForm','as'=>'register']);

    //user edit route here
    Route::get('/edit/{action}', ['uses'=>'Auth\RegisterController@showEditForm','as'=>'edituser']);
    Route::post('/register', 'Auth\RegisterController@register');

    Route::get('/list', ['uses'=>'Auth\RegisterController@index', 'as'=>'index']);
    Route::post('/permission_view', ['uses'=>'PermissionController@permission_view', 'as'=>'permission_view']);
    Route::get('/assign_permission/{id}', ['uses'=>'PermissionController@assign_permission', 'as'=>'assign_permission']);
    Route::post('/assign_permission/store', ['uses'=>'PermissionController@assign_permission_store', 'as'=>'assign_permission_store']);
    Route::post('/delete', ['uses'=>'Auth\RegisterController@delete', 'as'=>'delete']);
});

Route::group(['prefix' =>ROOT_DIR.'permission', 'middleware' => 'auth', 'as' => 'permission.'], function () {
    Route::get('/list', ['uses'=>'PermissionController@index','as'=>'index'])->middleware('can:user-add');
    Route::post('/add', ['uses'=>'PermissionController@create','as'=>'add'])->middleware('can:user-add');
    Route::post('/delete', ['uses'=>'PermissionController@delete','as'=>'delete'])->middleware('can:user-add');
});

Route::group(['prefix' =>ROOT_DIR.'file', 'middleware' => 'auth', 'as' => 'file.'], function () {
    Route::get('/status', ['uses'=>'FileController@get_file_status','as'=>'get_file_status']);
    // files count @MR
    Route::get('/count', ['uses'=>'FileController@getCount','as'=>'get_files_count']);
    Route::get('/ward_files/{id}', ['uses'=>'FileController@showFilesByWard','as'=>'get_files_by_ward']);
});

// CONSULTANCY ROUTE START
Route::group(['prefix' =>ROOT_DIR.'consultancy', 'middleware' => ['auth','can:consultancy'], 'as' => 'consultancy.'], function () {
    Route::get('/list', ['uses'=>'ConsultancyController@index','as'=>'index'])->middleware('can:consultancy');
    Route::get('/draft', ['uses'=>'ConsultancyController@get_draft','as'=>'draft'])->middleware('can:consultancy');
    Route::get('/add_form_personalinfo/{form_id?}', ['uses'=>'ConsultancyController@get_form_personalinfo','as'=>'add_form_personalinfo'])->middleware('can:consultancy');
    Route::post('/add_form_personalinfo', ['uses'=>'ConsultancyController@post_form_personalinfo','as'=>'store_form_personalinfo'])->middleware('can:consultancy');
    Route::get('/view_form/{form_id}', ['uses'=>'ConsultancyController@get_full_form','as'=>'view_full_form'])->middleware('can:consultancy');

    //form_landinfo routes
    Route::get('/add_form_landinfo/{form_id}', ['uses'=>'ConsultancyController@get_form_landinfo','as'=>'add_form_landinfo'])->middleware('can:consultancy');
    Route::get('/add_form_landinfo/{form_id}', ['uses'=>'ConsultancyController@get_form_landinfo','as'=>'add_form_landinfo'])->middleware('can:consultancy');
    Route::post('/add_form_landinfo', ['uses'=>'ConsultancyController@post_form_landinfo','as'=>'store_form_landinfo'])->middleware('can:consultancy');

    //page = 3 form_buildinginfo
    Route::get('/add_form_buildinginfo/{form_id}', ['uses'=>'ConsultancyController@get_form_buildinginfo','as'=>'add_form_buildinginfo'])->middleware('can:consultancy');
    Route::post('/add_form_buildinginfo', ['uses' => 'ConsultancyController@post_form_buildinginfo' , 'as' => 'store_form_buildinginfo'])->middleware('can:consultancy');

    //page = 4 form_floorinfo
    Route::get('/add_form_floorinfo/{form_id}', ['uses'=>'ConsultancyController@get_form_floorinfo','as'=>'add_form_floorinfo'])->middleware('can:consultancy');
    Route::post('/store_form_floorinfo', ['uses' => 'ConsultancyController@post_form_floorinfo' , 'as' => 'store_form_floorinfo'])->middleware('can:consultancy');

    //page = 5 form_buildingfiles
    Route::get('/add_form_buildingfiles/{form_id}', ['uses'=>'ConsultancyController@get_form_buildingfiles','as'=>'add_form_buildingfiles'])->middleware('can:consultancy');
    Route::post('/add_form_buildingfiles', ['uses' => 'ConsultancyController@post_form_buildingfiles' , 'as' => 'store_form_buildingfiles'])->middleware('can:consultancy');

    // rejected files
    Route::group(['prefix' =>'rejected', 'as'=>'rejected.'], function () {
        Route::get('/list', ['uses' => 'ConsultancyController@get_rejected_file' , 'as' => 'list'])->middleware('can:consultancy');

        //edit form
        Route::get('/edit_form/{form_id}', ['uses'=>'ConsultancyController@get_edit_form','as'=>'edit_form'])->middleware('can:consultancy');
        Route::post('/edit_form', ['uses'=>'ConsultancyController@post_edit_form','as'=>'post_edit_form'])->middleware('can:consultancy');

        //route to edit dpc
        Route::get('/edit_dpcform/{form_id}', ['uses'=>'ConsultancyController@get_edit_dpcform','as'=>'edit_dpcform'])->middleware('can:consultancy');

        //route to edit sampanna
        Route::get('/edit_sampanna/{form_id}', ['uses'=>'ConsultancyController@get_edit_sampanna','as'=>'edit_sampanna'])->middleware('can:consultancy');
    });

    // DPC
    Route::get('/list/dpc/{form_id}', ['uses'=>'ConsultancyController@get_dpc_form','as'=>'get_dpc_form'])->middleware('can:consultancy');
    Route::post('/dpc', ['uses'=>'ConsultancyController@post_dpc_form','as'=>'post_dpc_form'])->middleware('can:consultancy');
    Route::get('/dpc_view/{form_id}', ['uses'=>'ConsultancyController@get_dpc_view','as'=>'get_dpc_view'])->middleware('can:consultancy');
    Route::get('/view_dpc/{form_id}', ['uses'=>'ConsultancyController@get_upload_dpc','as'=>'view_dpc'])->middleware('can:consultancy');

    //dpc after print upload
    Route::post('/upload_dpc', ['uses'=>'ConsultancyController@post_upload_dpc','as'=>'uploaddpc'])->middleware('can:consultancy');

    // SAMPANNA
    Route::get('/sampanna/{form_id}', ['uses'=>'ConsultancyController@get_sampanna_form','as'=>'get_sampanna_form'])->middleware('can:consultancy');
    Route::post('/store_form_sampanna', ['uses'=>'ConsultancyController@post_form_sampanna','as'=>'store_form_sampanna'])->middleware('can:consultancy');
    Route::get('/upload_sampanna/{form_id}', ['uses'=>'ConsultancyController@get_upload_sampanna_form','as'=>'get_upload_sampanna_form'])->middleware('can:consultancy');

    //sampanna after print upload
    Route::post('/upload_sampanna', ['uses'=>'ConsultancyController@post_upload_sampanna','as'=>'uploadsampanna'])->middleware('can:consultancy');
    Route::get('/view_sampanna/{form_id}', ['uses'=>'ConsultancyController@get_view_sampanna','as'=>'view_sampanna'])->middleware('can:consultancy');

    //change house_map
    Route::get('/view_housemap/{form_id}', ['uses'=>'ConsultancyController@get_housemap','as'=>'view_housemap'])->middleware('can:consultancy');
    Route::post('/change_housemap', ['uses'=>'ConsultancyController@post_change_housemap','as'=>'change_housemap'])->middleware('can:consultancy');
});

// AAMIN ROUTE
Route::group(['prefix' =>ROOT_DIR.'aamin', 'middleware' => 'auth', 'as' => 'aamin.'], function () {
    Route::get('/list', ['uses'=>'AaminController@index','as'=>'index'])->middleware('can:aamin');
    Route::get('/view_sandhir/{form_id}', ['uses'=>'AaminController@get_sandhir','as'=>'view_sandhir'])->middleware('can:aamin');
    Route::post('/view_sandhir', ['uses' => 'AaminController@store_aaminPratibedan' , 'as' => 'store_aaminPratibedan'])->middleware('can:aamin');
    Route::get('/view_aamin_pratibedan/{form_id}', ['uses' => 'AaminController@get_aaminPratibedan' , 'as' =>'view_aamin'])->middleware('can:aamin');

    //to display the rejected files.
    Route::get('/list_rejected', ['uses' => 'AaminController@get_rejected_file' , 'as' =>'list_rejected'])->middleware('can:aamin');

    //to edit the aamin_pratibedan form.
    Route::get('/edit_form/{form_id}', ['uses' => 'AaminController@editAaminPratibedan' , 'as' =>'edit_aaminPratibedan'])->middleware('can:aamin');

    //to store uploaded aamin_pratibedan form
    Route::post('/aamin_pratibedan_upload', ['uses' => 'AaminController@store_aaminPratibedanUpload' , 'as' => 'upload_aaminPratibedan'])->middleware('can:aamin');

resources/views/layouts/_partials/head.blade.php
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
	<link rel="icon" type="image/png" sizes="16x16" href="{{ asset(STATIC_DIR.'uploads/logo/logo.png') }}">
	<title>EBPS | @yield('page_title')</title>
	<!-- Bootstrap Core CSS -->
	<link href="{{ asset(STATIC_DIR.'assets/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    @yield('css-top')

    <link href="{{ asset(STATIC_DIR.'plugins/bower_components/datatables/jquery.dataTables.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css" rel="stylesheet" type="text/css" />

    <!-- Menu CSS -->
	<link href="{{ asset(STATIC_DIR.'plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css') }}" rel="stylesheet">
	<!-- animation CSS -->
	<link href="{{ asset(STATIC_DIR.'plugins/bower_components/toast-master/css/jquery.toast.css') }}" rel="stylesheet">
	<link href="{{ asset(STATIC_DIR.'assets/css/animate.css') }}" rel="stylesheet">
	<!-- Custom CSS -->
	<link href="{{ asset(STATIC_DIR.'assets/css/style.css') }}" rel="stylesheet">
	<!-- color CSS -->
	<link href="{{ asset(STATIC_DIR.'assets/css/colors/megna-dark.css') }}" id="theme" rel="stylesheet">

	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <link rel="stylesheet" href="{{ asset(STATIC_DIR.'css/custom.css') }}">
	@yield('css')
	<style>
		.action{
			display: none;
		}
		.title:hover .action {
			display: block;
			margin-left: -12px;
		}
		.vl {
		    border-left: 1px solid green;
		    height: 2px;
		}
		.sidebar .label {
			margin-top: -2px;
		}
		.sidebar-label{
			color: white;
			font-weight: bold;
			letter-spacing: 8px;
			padding-bottom: 15px;
			padding-top: 15px;
		}
	</style>
</head>

resources/views/layouts/_partials/messages.blade.php
@if(Session::has('success'))
    <div class="row">
        <div class="col-md-12">
            <div id="message" class="updated notice notice-success is-dismissible alert alert-dismissable" style="width:100%;">
                <p>
                    <strong>
                        {{Session::get('success')}}
                    </strong>
                </p>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="margin-top:-25px; margin-right:8px;padding-right:5px;">
                    <i class="mdi mdi-close"></i>
                </button>
            </div>
        </div>
    </div>
    <br>
@endif

resources/views/layouts/_partials/print-head.blade.php
<div class="row print-head" style="display: none;margin-top: -50px;">
	<div class="col-md-3">
		<img src="{{ asset(STATIC_DIR.'uploads/logo/logo.png') }}" alt="" width="70">
		
	</div>
	<div class="col-md-6 text-center" style="margin-top: -90px;">
		<h2 style="margin-bottom: -15px;">रत्ननगर  नगरपालिका </h2>
		<h4 style="margin-bottom: -1px;">नगर कार्यपालिकाको कार्यालय</h4>
		<p style="margin-bottom: -15px;">रत्ननगर, चितवन, ३ नं प्रदेश नेपाल </p>
		<h4 style="margin-bottom: -15px;">भुकम्प सुरक्षा तथा घरनक्शा महाशाखा</h4>
	</div>
	<div class="col-md-3 text-right" style="margin-top: -80px; padding-bottom: 50px">
		<p>फोन नं : ५६०५२९,५६२४३६</p>
		<p>FAX : ०५६-५६०५२९</p>
	</div>
</div>

resources/views/layouts/_partials/scripts.blade.php
<!-- /#wrapper -->
<!-- jQuery -->
<script src="{{ asset(STATIC_DIR.'plugins/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{{ asset(STATIC_DIR.'assets/bootstrap/dist/js/bootstrap.min.js') }}"></script>

<script src="{{ asset(STATIC_DIR.'plugins/bower_components/datatables/jquery.dataTables.min.js') }}"></script>
<!-- Sidebar menu plugin JavaScript -->
<script src="{{ asset(STATIC_DIR.'plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js') }}"></script>
<!--Slimscroll JavaScript For custom scroll-->
<script src="{{ asset(STATIC_DIR.'assets/js/jquery.slimscroll.js') }}"></script>
<!--Wave Effects -->
<script src="{{ asset(STATIC_DIR.'assets/js/waves.js') }}"></script>
<!-- Custom Theme JavaScript -->
@yield('scripts')
<script src="{{ asset(STATIC_DIR.'assets/js/custom.js') }}"></script>
<script src="{{ asset(STATIC_DIR.'plugins/bower_components/styleswitcher/jQuery.style.switcher.js') }}"></script>

resources/views/layouts/_partials/sidebar.blade.php
<?php
$count = App\Helper\Tools::count_file();
?>
<div class="navbar-default sidebar hide-on-print" role="navigation">
	<div class="sidebar-nav slimscrollsidebar">
		<div class="sidebar-head">
			<h3>
                <span class="fa-fw open-close">
                    <i class="ti-close ti-menu"></i>
                </span> <span class="hide-menu">Navigation</span></h3>
		</div>
		<ul class="nav" id="side-menu">
			<li class="user-pro">
				<a href="#" class="waves-effect @if(Request::is('profile')) active @endif">

					@if(!empty(Auth::user()->avatar))
						<img src="{{ asset(STATIC_DIR.'storage/'.Auth::user()->avatar) }}" alt="user"  class="img-circle" />
					@else
						<img src="{{ asset(STATIC_DIR.'uploads/defualt.png') }}" alt="user"  class="img-circle" />
					@endif

					{{--<img src="{{ asset(STATIC_DIR.'uploads/defualt.png') }}" alt="user-img" class="img-circle">--}}
					<span class="hide-menu"> {{ Auth::user()->first_name }} {{ Auth::user()->last_name }}<span class="fa arrow" style="padding-top:10px;"></span>
                    </span>
				</a>
				<ul class="nav nav-second-level collapse" aria-expanded="true" style="height: @if(Request::is('profile')) 62px @endif;">
					<li>
						<a href="{{ route('profile') }}" class="waves-effect @if(Request::is('profile')) active @endif"  >
							<i class="ti-user"></i>
							<span class="hide-menu">My Profile</span>
						</a>
					</li>

					<!-- <li><a href="javascript:void(0)"><i class="ti-settings"></i> <span class="hide-menu">Account Setting</span></a></li> -->
					<li style="padding-left: 12px;">
						<form id="logout-form" action="{{ route('logout') }}" method="POST" >
							@csrf
							<button type="submit" class="btn btn-link btn-flat text-danger"><i class="fa fa-power-off"></i>&nbsp;Logout</button>
						</form>
					</li>
				</ul>
			</li>
			<li> <a href="{{ route('home') }}" class="waves-effect @if(Request::is('/')) active @endif ">
					<i class="mdi mdi-av-timer fa-fw"></i>
					<span class="hide-menu">Dashboard</span>
				</a>
			</li>


			@can('permission-list')
				<li> <a href="{{ route('permission.index') }}" class="@if(Request::is('permission/*')) active @endif">
						<i class="mdi mdi-lock fa-fw" data-icon="v"></i>
						<span class="hide-menu"> Permissions</span>
					</a>
				</li>
			@endcan

			@can('administration')
				<li>
					<a href="#" class="waves-effect @if(Request::is('user/*')) active @endif">
						<i class="mdi mdi-account-multiple fa-fw"></i>
						<span class="hide-menu">Users<span class="fa arrow open"></span></span>
					</a>
					<ul class="nav nav-second-level @if(Request::is('user/*')) collapse in @endif">
						<li>
							<a class="@if(Request::is('user/register')) active @endif" href="{{ route('user.register') }}">
								<i class="mdi mdi-account-multiple-plus fa-fw"></i> <span class="hide-menu">Add</span>
							</a>
						</li>
						<li>
							<a class="@if(Request::is('user/list')) active @endif" href="{{ route('user.index') }}">
								<i class="mdi mdi-format-list-bulleted fa-fw"></i> <span class="hide-menu">List</span>
							</a>
						</li>
					</ul>
				</li>

				{{--<li class="devider"></li>--}}
				{{--<li class="" style="color: white;">&nbsp;&nbsp;Engineer</li>--}}
				<li class="devider"></li>
				<li>
					<a href="{{ route('administration.get_files') }}" class="@if(Request::is('administration/get_files')) active @endif">
						<i class="mdi mdi-format-list-bulleted fa-fw" data-icon="v"></i>
						<span class="hide-menu"> All Files </span>
					</a>
				</li>
                <li>
                    <a href="{{ route('file.get_files_count') }}" class="@if(Request::is('file/count') || Request::is('file/ward_files/*')) active @endif">
                        <i class="mdi mdi-file-multiple fa-fw" data-icon="v"></i>
                        {{-- <i class="far fa-tally"></i> --}}
                        <span class="hide-menu"> Files by Ward </span>
                    </a>
                </li>
				<li>
					<a href="{{ route('file.get_file_status') }}" class="@if(Request::is('file/status')) active @endif">
						<i class="mdi mdi-checkbox-multiple-marked fa-fw" data-icon="v"></i>
						<span class="hide-menu"> File Tracker</span>
					</a>
                </li>

			@endcan
			@can('consultancy')
				<li class="devider"></li>
				<li class="text-center text-uppercase sidebar-label">Consultancy</li>
				<li class="devider"></li>
				<li>
					<a href="{{ route('consultancy.add_form_personalinfo') }}" class="@if(Request::is('consultancy/add_form_personalinfo') OR Request::is('consultancy/add_form_landinfo/*')) active @endif">
						<i class="mdi mdi-file-document fa-fw" data-icon="v"></i>
						<span class="hide-menu"> Create New File</span>
					</a>
				</li>
				<li>
					<a href="{{ route('consultancy.index') }}" class="@if(Request::is('consultancy/list') OR Request::is('consultancy/list/*')) active @endif">
						<i class="mdi mdi-format-list-bulleted fa-fw" data-icon="v"></i>
						<span class="hide-menu"> File Listing</span>
					</a>
				</li>

				<li>
					<a href="{{ route('consultancy.draft') }}" class="@if(Request::is('consultancy/draft') OR Request::is('consultancy/draft/*')) active @endif">
						<i class="mdi mdi-file-cloud fa-fw" data-icon="v"></i>
						<span class="hide-menu">Draft Files
							@if($count['draft'] > 0)
								<span class="label label-rouded label-warning pull-right" style="font-weight: bold ">{{$count['draft'] ?? ''}}</span>
							@endif
						</span>
					</a>
				</li>
				<li>
					<a href="{{ route('consultancy.rejected.list') }}" class="@if(Request::is('consultancy/rejected/*') OR Request::is('consultancy/rejected/*')) active @endif">
						<i class="mdi mdi-file-excel fa-fw" data-icon="v"></i>

						<span class="hide-menu"> Rejected Files
							@if($count['rejected'] > 0)
								<span class="label label-rouded label-danger pull-right" style="font-weight: bold ">{{$count['rejected']}}</span>
							@endif
						</span>
					</a>
				</li>
			@endcan

			@can('sub-engineer')
				<li class="devider"></li>
				<li class="text-center text-uppercase sidebar-label">Sub Engineer</li>
				<li class="devider"></li>
				<li>
					<a href="{{ route('subengineer.index') }}" class="@if(Request::is('subengineer/list')) active @endif">
						<i class="mdi mdi-format-list-bulleted fa-fw" data-icon="v"></i>
						<span class="hide-menu"> File Listing</span>
					</a>
				</li>
				<li>
					<a href="{{ route('file.get_file_status') }}" class="@if(Request::is('file/status')) active @endif">
						<i class="mdi mdi-checkbox-multiple-marked fa-fw" data-icon="v"></i>
						<span class="hide-menu"> File Tracker</span>
					</a>
				</li>
			@endcan

			@can('engineer')
				<li class="devider"></li>
				<li class="text-center text-uppercase sidebar-label">Engineer</li>
				<li class="devider"></li>
				<li>
					<a href="{{ route('engineer.index') }}" class="@if(Request::is('engineer/list')) active @endif">
						<i class="mdi mdi-format-list-bulleted fa-fw" data-icon="v"></i>
						<span class="hide-menu"> File Listing</span>
					</a>
				</li>

				<li>
					<a href="{{ route('file.get_file_status') }}" class="@if(Request::is('file/status')) active @endif">
						<i class="mdi mdi-checkbox-multiple-marked fa-fw" data-icon="v"></i>
						<span class="hide-menu"> File Tracker</span>
					</a>
				</li>
			@endcan

			@can('main-engineer')
				<li class="devider"></li>
				<li class="text-center text-uppercase sidebar-label">Main Engineer</li>
				<li class="devider"></li>
				<li> <a href="{{ route('mainengineer.index') }}" class="@if(Request::is('mainengineer/list')) active @endif">
						<i class="mdi mdi-format-list-bulleted fa-fw" data-icon="v"></i>
						<span class="hide-menu"> File Listing</span>
					</a>
				</li>
				<li>
					<a href="{{ route('file.get_file_status') }}" class="@if(Request::is('file/status')) active @endif">
						<i class="mdi mdi-checkbox-multiple-marked fa-fw" data-icon="v"></i>
						<span class="hide-menu"> File Tracker</span>
					</a>
				</li>
			@endcan

			@can('aamin')
				<li class="devider"></li>
				<li class="text-center text-uppercase sidebar-label">Aamin</li>
				<li class="devider"></li>
				<li> <a href="{{ route('aamin.index') }}" class="@if(Request::is('aamin/list')) active @endif">
						<i class="mdi mdi-format-list-bulleted fa-fw" data-icon="v"></i>
						<span class="hide-menu"> File Listing</span>
					</a>
				</li>
				<li>
					<a href="{{ route('aamin.list_rejected') }}" class="@if(Request::is('consultancy/list_rejected')) active @endif">
						<i class="mdi mdi-file-excel fa-fw" data-icon="v"></i>
						<span class="hide-menu"> Rejected Files
							@if($count['rejected_aamin'] > 0)
								<sup>
									<span class="badge badge-danger" style="font-size: 9px !important;">
										{{$count['rejected_aamin']}}
									</span>
								</sup>
							@endif
						</span>
					</a>
				</li>
				<li>
					<a href="{{ route('file.get_file_status') }}" class="@if(Request::is('file/status')) active @endif">
						<i class="mdi mdi-checkbox-multiple-marked fa-fw" data-icon="v"></i>
						<span class="hide-menu"> File Tracker</span>
					</a>
				</li>
			@endcan
			<li style="padding-bottom: 100px;"></li>
		</ul>
	</div>
</div>